### ISSUE TITLE
"MR" & "GearboxAddon" Compatibility

### ISSUE THREAD

**Issue by Dwinesk** [TyKonKet/FS17_FuelUsageDisplay#35]
Hi TykonKet. I want to start by thanking you for all your hard work and the marvelous creations that you and your collaborators have given to the farm sim community. On to the FuelUsageDisplay, I really enjoyed using this mod but unfortunately I have had to give up on using it as it isn't compatible with the 'MR'(morerealistic) mod. As I (and I'm sure I'm not alone when I say this) want to inject more realism into the game 'mr' is indispensable. So my question to you is... Is it possible to make them compatible.

Here is a link to the 'mr' forum. The author Dural is always helpful and I know that you two programming geniuses can make it happen: https://fs-uk.com/forum/index.php?topic=195659.0

**Comment by TyKonKet** [comment]
Hi, I'm finally back home and ready for working on my mods.
Can you please explain more detail what kind of problems have the fuel usage with MR?

**Comment by Dzi4d3k** [comment]
@TyKonKet 
I think that this is the case post:
https://www.fs-uk.com/forum/index.php?topic=195661.msg1273342#msg1273342
Maybe the solution is to auto-deactivate your mod on MR-converted vehicles and activate only on non-MR?

**Comment by TyKonKet** [comment]
Nono, i want fix it in the right way, any suggestions on how to reproduce the issues?

**Comment by fcucino** [comment]
> - better fuel usage mod -> lose of power, incorrect fuel usage 

Just the time to find some topic where users explain the problem and I will send you
https://www.fs-uk.com/forum/index.php?topic=195659.msg1273124#msg1273124

**Comment by fcucino** [comment]
https://www.fs-uk.com/forum/index.php?topic=195659.msg1274070#msg1274070
https://www.fs-uk.com/forum/index.php?topic=195659.msg1274075#msg1274075

**Comment by TyKonKet** [comment]
dove posso trovare un trattore che abbia questo genere di problemi?

**Comment by fcucino** [comment]
I trattori originali "sovrascritti" dalla mod che trovi in moreRealistic.zip\data\vehiclesOverriding\_database.xml
Il download lo trovi qui: https://www.fs-uk.com/forum/index.php?topic=195659.msg1273121#msg1273121
P.S.: Non ho mai testato personalmente mr + better fuel usage e ti riporto quello che segnalano altri

**Comment by TyKonKet** [comment]
> I trattori originali "sovrascritti" dalla mod che trovi in moreRealistic.zip\data\vehiclesOverriding_database.xml
Il download lo trovi qui: https://www.fs-uk.com/forum/index.php?topic=195659.msg1273121#msg1273121
P.S.: Non ho mai testato personalmente mr + better fuel usage e ti riporto quello che segnalano altri

Ok proverò meglio, ma da quello che ho visto con un test veloce, sembra che con l'ultima versione di mr non ci siano grossi problemi.

**Comment by Dwinesk** [comment]
I had stopped using it on a previous version of 'mr' which froze the controls when used together. The current version does work but because your mod overwrites some of the same vales as 'mr' yours are used instead of 'mr'. A good example is the JYMPA ripper/plough mod (can be found on the GIANTS mod hub) the 5.7m variant cannot be used with better fuel as it causes the implement to skip along the ground. 'MR' had a similar issue but it was fixed there. I suggest if possible:

1). Insert code into your mod that deactivate certain features if 'mr' is detected to be active in the mod folder.
or
2). Create an 'mr' specific version of your mod that lacks the things that 'mr' will take care of e.g. the tool power requirements and other physics just to mention a few.

**Comment by TyKonKet** [comment]
I'm going to disable conflicting features when a vehicle is mr, in this way we will get the best of both mods.

**Comment by Dzi4d3k** [comment]
I think it is good compromise, but will we still have the visual effects of fuel usage in MR vehicles?

**Comment by Dwinesk** [comment]
I agree to that. I'm sure people on here will test the changes and advise accordingly... Question though, some features of 'mr' were applied to vehicles even if they were not specifically an 'mr' vehicle. How do you plan to deal with that? Could it be set up such that if 'mr' is present your mod prioritizes using those conflicting vales provided by 'mr' rather than it's own..? Or am I thinking too much into it?

**Comment by TyKonKet** [comment]
> I think it is good compromise, but will we still have the visual effects of fuel usage in MR vehicles?

Sure!

**Comment by TyKonKet** [comment]
> I agree to that. I'm sure people on here will test the changes and advise accordingly... Question though, some features of 'mr' were applied to vehicles even if they were not specifically an 'mr' vehicle. How do you plan to deal with that? Could it be set up such that if 'mr' is present your mod prioritizes using those conflicting vales provided by 'mr' rather than it's own..? Or am I thinking too much into it?

I can easily know if mr is "installed" and if a vehicle is full or partial mr, so i can change behaviour of bfu based on that.

**Comment by TyKonKet** [comment]
Guys, if you want to try this version and let me know, i would be glad 😄

**Comment by Dwinesk** [comment]
Initial tests show that the display you have on the inside of the speedometer is deactivated on all  default in-game vehicles... I'm guessing cause they all count as 'mr' vehicles. Is there a way to still have it functioning? Now back to more testing.

**Comment by TyKonKet** [comment]
Please send some screenshots because with mr vehicles i don't find any problems.

**Comment by Dwinesk** [comment]
@TyKonKet 
![20170704154046_1](https://user-images.githubusercontent.com/29665879/27830683-3565dbec-60d0-11e7-93f0-da1dae677a59.jpg)
![20170704154200_1](https://user-images.githubusercontent.com/29665879/27830703-49328b84-60d0-11e7-9f22-a2ef790bb643.jpg)

First pic is of the Big Bud 450 from the DLC. (I'm sure this is not an 'mr' vehicle cause of GIANTS "hidding" the code so people have to buy it or else it would probably end up as a mod).
Second is on an in-game truck. 

In both cases the vehicle is on. I even have given it some gas. As you can see the truck has the bar in the speedo but it doesn't animate.

**Comment by fcucino** [comment]
Sorry @Dwinesk , but I wrote in Italian so I can speak easily with Tykon.
@TyKonKet , con un veicolo mr c'è il comando "debugf" o "debug" (non ricordo se sia stato cambiato dal primo al secondo) e dovrebbe esserci fra tutte le informazioni anche il consumo attuale. Potresti chiedere a Dural se è possibile chiamare la sua funzione di calcolo consumi e visualizzarla nell'hud anziché lasciare giustamente vuoto per non fare conflitti

**Comment by TyKonKet** [comment]
@turbostar190 il consumo me lo calcolo già semplicemente facendo via via la differenza di carburante presente, infatti ora con i veicoli mr funziona, da quello che ho capito sembra che non funzionino più tutti gli altri veicoli.

**Comment by fcucino** [comment]
Appena torno a casa proverò anche io, ma penso che Dwinesk intenda che sui veicoli mr non si veda più il contatore animato interno al contatore Giants della velocità

**Comment by Dwinesk** [comment]
I have also noticed that the exhaust effects that your mod gives to vehicles seems to be affected by the issue I pointed out above. On in-game vehicles instead of transparent-white-black smoke your mod used to give (depending on the engine load) now there is a constant black/transparent smoke "cone/box". Not pleasant at all. Mod vehicles still get the great effects.

**Comment by Dwinesk** [comment]
![20170704202302_1](https://user-images.githubusercontent.com/29665879/27839098-7236fd90-60f7-11e7-8155-55b9973d0a29.jpg)
![20170704202336_1](https://user-images.githubusercontent.com/29665879/27839106-8148ea6e-60f7-11e7-976e-3142bb63dc6a.jpg)

In these pictures you can see the exhaust effect on in-game vehicles with 'bfu' enabled. Also, please take note of the fuel consumption figures. 1st pic, cruise control is on 'bfu' fuel usage matches 'gearbox addon' (within margin of error). 2nd pic, I just let off the accelerator and let the tractor coast and the fuel usage immediately fell to 0 "zero" in both meters. I'm sure that shouldn't be the case. Vehicles should only read zero fuel usage when off.

**Comment by Dzi4d3k** [comment]
This is also the case when you are braking with engine. Every car computer will show you that, I can't imagine why tractors should be different.

**Comment by fcucino** [comment]
@TyKonKet Io ho provato **mr + bfu** e funziona, ma non sempre. Con gli operai inseriti o in decelerazione il valore segnato dalla **bfu** diventa 0, mentre rimane sempre giusto quello reale visibile con il comando console "debug" della **mr**. Con i veicoli **non mr** non ci sono problemi

**Comment by fcucino** [comment]
E dimenticavo di menzionare il brusco cambio di consumi visualizzati, anche sullo stesso tipo di terreno, dovuti a minimi cambi di rpm ma attribuibili in principio alla mr, perché anche nella modalità "debug" sono presenti

**Comment by TyKonKet** [comment]
Io al momento ho fatto come mi avete chiesto voi, ovvero se un veicolo è MR, disattivo la mia funzione di consumo e lascio quella MR, limitandomi solo mostrare il consumo (quello che viene mostrato nella schermata debug). Quindi se quando lasci l'acceleratore il consumo va a 0 o se ci sono bruschi cambi di consumo attualmente non dipende più da me ma dalla MR e di conseguenza dovete parlare con Dural.
Se invece non funziona il l'indicatore del carico del motore o l'effetto di scarico, quello dipende ancora da me e devo fixarlo.

At the moment I did as you asked me, that is, if a vehicle is MR, I disable my consumption function and leave the MR one, limiting my work only to display consumption (the one is shown in the debug screen). So if when you leave the accelerator the consumption goes to 0 or if there are abrupt changes in consumption it no longer depends on me but from MR and consequently you have to talk to Dural.
If, however, the engine load indicator or exhaust effect does not work, that still depends on me and I have to fix it.

**Comment by TyKonKet** [comment]
About gearbox, I still need to investigate what happens.

**Comment by TyKonKet** [comment]
@Dwinesk I don't understand how you can encounter this kind of problems since MR + GearBox doesn't work together.

**Comment by Dzi4d3k** [comment]
@TyKonKet 
They do, all you have to do is to use latest GearBox version from GitHub:
https://github.com/Mogli12/GearboxAddon/blob/master/FS17_GearboxAddon.zip

**Comment by Dzi4d3k** [comment]
@TyKonKet 
Things are changing very fast:
https://www.fs-uk.com/forum/index.php?topic=195659.msg1282928#msg1282928

**Comment by Dwinesk** [comment]
@TyKonKet 'mr' & gearox addon do work together. Get the latest gearbox addon here on github. It is updated very regularly.

**Comment by TyKonKet** [comment]
Fixed with b1f8dda

**Comment by fcucino** [comment]
Dopo l'ultimo update, non sapendo se sia intenzionale o no, mentre l'operaio è inserito viene visualizzato il consumo medio nell'hud e non quello reale (entrambi calcolati dalla mr). Inoltre prossimamente ti farò sapere se è effettivamente un bug un comportamento strano che ho notato in alcune situazioni.

**Comment by TyKonKet** [comment]
@turbostar190 la questione è la seguente:
Se hai impostato a l'operaio di comprare il carburante, la funzione di consumo carburante, invece di sottrarre il carburante ti fa spendere i soldi corrispondenti e di conseguenza non c'è modo di sapere quanto carburante sta venendo consumato quando la funzione di consumo carburante è definita da more realistic o gearbox.
L'unica cosa che ho potuto fare è stato andare a leggere i valori calcolati da loro e mostrare quelli, nonostante questo ci sono ancora tre gravi problemi:
1) L'unico dato disponibile (quando c'è solo mr senza gearbox) è la media
2) La media viene calcolata solo se abiliti il debug
3) Il consumo della gearbox (quando è attivo l'operaio) tiene conto solo del consumo "a riposo" del motore

PS:
Il problema di fondo è che sia il creatore della mr che gb sono un po' troppo egocentrici e quando fanno mods pensano solo per se e non agli altri modders, gli ci voleva poco a mettere una variabile con il consumo che le altre mods potessero leggere, ma invece non gli frega niente quindi più di così non si può fare.

**Comment by Dzi4d3k** [comment]
> a mettere una variabile con il consumo che le altre mods potessero leggere

@TyKonKet 
Have you tried to ask dural at FSUK
https://www.fs-uk.com/forum/index.php?topic=195659.0
I saw that dural changed many things on users requests

or Mogli12 here:
https://github.com/Mogli12/GearboxAddon/issues
 
I think is it worth trying to ask both of them, as your mod adds great values to overall game experience.

**Comment by TyKonKet** [comment]
This is the answer of Mogli:
https://www.fs-uk.com/forum/index.php?topic=195659.msg1283083#msg1283083

I can't do nothing if they don't want do nothing.

**Comment by Dwinesk** [comment]
@TyKonKet Well no matter what is going on with those other modders I'd like to say nice work on your part. You have done what you can on your end and it is marvelous. Hopefully one day all the egos involved can quiet down to perfect it. Optimistically looking forward to that if it does come to pass.
